# .golangci.yml
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  errcheck:
    check-blank: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    # Exclude TUI package - not actively used in v1.0.x (GUI uses Wails)
    - path: internal/tui/
      linters:
        - errcheck
        - unused
        - gofmt
        - gosimple
        - ineffassign
        - misspell
        - staticcheck
