# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: dev-cleaner

before:
  hooks:
    - go mod tidy
    # Create dummy frontend/dist for main.go embed directive
    - mkdir -p frontend/dist && touch frontend/dist/.gitkeep
    # Test only CLI packages (exclude root main.go which requires frontend/dist)
    - go test ./cmd/... ./internal/... ./pkg/...

builds:
  - id: dev-cleaner
    main: ./cmd/dev-cleaner/main.go
    binary: dev-cleaner
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/thanhdevapp/dev-cleaner/cmd/root.Version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: dev-cleaner
    repository:
      owner: thanhdevapp
      name: homebrew-tools
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/thanhdevapp/mac-dev-cleaner-cli"
    description: "Clean development artifacts on macOS - Xcode, Gradle, node_modules"
    license: "MIT"
    install: |
      bin.install "dev-cleaner"
    test: |
      system "#{bin}/dev-cleaner", "--version"

release:
  github:
    owner: thanhdevapp
    name: mac-dev-cleaner-cli
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

# Announce to social (optional)
# announce:
#   twitter:
#     enabled: false
