// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clean(arg1) {
  return window['go']['main']['App']['Clean'](arg1);
}

export function ClearTreeCache() {
  return window['go']['main']['App']['ClearTreeCache']();
}

export function GetScanResults() {
  return window['go']['main']['App']['GetScanResults']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTreeNode(arg1, arg2) {
  return window['go']['main']['App']['GetTreeNode'](arg1, arg2);
}

export function IsCleaning() {
  return window['go']['main']['App']['IsCleaning']();
}

export function IsScanning() {
  return window['go']['main']['App']['IsScanning']();
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
