// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {cleaner} from '../models';
import {services} from '../models';

export function Clean(arg1:Array<types.ScanResult>):Promise<Array<cleaner.CleanResult>>;

export function ClearTreeCache():Promise<void>;

export function GetScanResults():Promise<Array<types.ScanResult>>;

export function GetSettings():Promise<services.Settings>;

export function GetTreeNode(arg1:string,arg2:number):Promise<types.TreeNode>;

export function IsCleaning():Promise<boolean>;

export function IsScanning():Promise<boolean>;

export function Scan(arg1:types.ScanOptions):Promise<void>;

export function UpdateSettings(arg1:services.Settings):Promise<void>;
